import{a as w,S as v,i as s}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();const S="https://pixabay.com/api/",$="47590180-dc1d7afa62bd02f66448b190c";async function f(e,r=1,l=9){const a=`${S}?key=${$}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${l}&page=${r}`,t=await w.get(a);if(t.status!==200)throw new Error("Failed to fetch images");return t.data}let u;function m(e){const r=document.querySelector(".gallery"),l=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:c,views:h,comments:b,downloads:L})=>`
        <a class="gallery-item" href="${t}">
            <img src="${a}" alt="${o}" loading="lazy" />
            <div class="info">
                <p><b>Likes:</b> ${c}</p>
                <p><b>Views:</b> ${h}</p>
                <p><b>Comments:</b> ${b}</p>
                <p><b>Downloads:</b> ${L}</p>
            </div>
        </a>
    `).join("");r.insertAdjacentHTML("beforeend",l),u?u.refresh():u=new v(".gallery-item",{captionsData:"alt",captionDelay:250})}function E(){const e=document.querySelector(".gallery");e.innerHTML=""}console.log("main.js loaded");const q=document.querySelector(".search-container"),P=document.querySelector("#search-input"),y=document.createElement("div"),n=document.createElement("button");n.textContent="Load more";n.classList.add("load-more");n.style.display="none";document.body.append(y,n);y.classList.add("gallery");let d="",i=1;q.addEventListener("click",async e=>{if(e.preventDefault(),d=P.value.trim(),!d){s.warning({title:"Warning",message:"Please enter a search term!"});return}i=1,E(),n.style.display="none",p();try{const r=await f(d,i);r.hits.length===0?s.info({title:"Info",message:"No images found. Try a different query!"}):(m(r.hits),n.style.display="block",i*9>=36&&(n.style.display="none",s.info({title:"Info",message:"You've reached the end of search results."})))}catch{s.error({title:"Error",message:"Something went wrong. Please try again!"})}finally{g()}});n.addEventListener("click",async()=>{i+=1,p();try{const e=await f(d,i);m(e.hits),i*9>=36&&(n.style.display="none",s.info({title:"Info",message:"You've reached the end of search results."})),I()}catch{s.error({title:"Error",message:"Something went wrong. Please try again!"})}finally{g()}});function p(){const e=document.createElement("div");e.classList.add("loader"),e.textContent="Loading...",document.body.append(e)}function g(){const e=document.querySelector(".loader");e&&e.remove()}function I(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
