import{a as v,S as w,i as c}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const $="https://pixabay.com/api/",E="47590180-dc1d7afa62bd02f66448b190c";async function m(t,r=1,n=15){const s=`${$}?key=${E}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${n}&page=${r}`,e=await v.get(s);if(e.status!==200)throw new Error("Failed to fetch images");return e.data}let d;function f(t){const r=document.querySelector(".gallery"),n=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:l,views:h,comments:b,downloads:L})=>`
        <a class="gallery-item" href="${e}">
            <img src="${s}" alt="${o}" loading="lazy" />
            <div class="info">
                <p><b>Likes:</b> ${l}</p>
                <p><b>Views:</b> ${h}</p>
                <p><b>Comments:</b> ${b}</p>
                <p><b>Downloads:</b> ${L}</p>
            </div>
        </a>
    `).join("");r.insertAdjacentHTML("beforeend",n),d?d.refresh():d=new w(".gallery-item",{captionsData:"alt",captionDelay:250})}function S(){const t=document.querySelector(".gallery");t.innerHTML=""}let i=1,u="";const q=document.querySelector(".search-container"),P=document.querySelector("#search-input"),y=document.createElement("div");y.classList.add("gallery");document.body.append(y);const a=document.createElement("button");a.textContent="Load more";a.classList.add("load-more");a.style.display="none";document.body.append(a);q.addEventListener("submit",async t=>{t.preventDefault();const r=P.value.trim();if(!r){c.warning({title:"Warning",message:"Please enter a search term!"});return}u=r,i=1,S(),a.style.display="none",p();try{const n=await m(u,i);n.hits.length===0?c.info({title:"Info",message:"No images found. Try another search!"}):(f(n.hits),i*15<n.totalHits&&(a.style.display="block"))}catch{c.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{g()}});a.addEventListener("click",async()=>{i+=1,p(a);try{const t=await m(u,i);f(t.hits),i*15>=t.totalHits&&(a.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),x()}catch{c.error({title:"Error",message:"Failed to load more images. Try again later!"})}finally{g(a)}});function p(t=document.body){const r=document.createElement("div");r.classList.add("loader"),r.textContent="Loading...",t.append(r)}function g(t=document.body){const r=t.querySelector(".loader");r&&r.remove()}function x(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
