import{S as m,i as s}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const p="https://pixabay.com/api/",g="47590180-dc1d7afa62bd02f66448b190c";function y(t,o=1,n=9){const a=`${p}?key=${g}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${n}&page=${o}`;return console.log("Generated URL:",a),fetch(a).then(e=>{if(!e.ok)throw console.error(`HTTP Error: ${e.status}`),new Error(`Failed to fetch images: ${e.statusText}`);return e.json()}).then(e=>(console.log("API Response:",e),e)).catch(e=>{throw console.error("Fetch Error:",e),e})}let c;function h(t){const o=document.querySelector(".gallery"),n=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:i,views:d,comments:u,downloads:f})=>`
        <a class="gallery-item" href="${e}">
            <img src="${a}" alt="${r}" loading="lazy" />
            <div class="info">
                <p><b>Likes:</b> ${i}</p>
                <p><b>Views:</b> ${d}</p>
                <p><b>Comments:</b> ${u}</p>
                <p><b>Downloads:</b> ${f}</p>
            </div>
        </a>
    `).join("");o.insertAdjacentHTML("beforeend",n),c?c.refresh():c=new m(".gallery-item",{captionsData:"alt",captionDelay:250})}function b(){const t=document.querySelector(".gallery");t.innerHTML=""}console.log("main.js loaded");const L=document.querySelector(".search-container"),$=document.querySelector("#search-input"),l=document.createElement("div");l.classList.add("gallery");document.body.append(l);L.addEventListener("click",async t=>{t.preventDefault();const o=$.value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search term!"});return}b(),w();try{const n=await y(o);n.hits.length===0?s.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):h(n.hits)}catch{s.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{S()}});function w(){const t=document.createElement("div");t.classList.add("loader"),t.textContent="Loading...",document.body.append(t)}function S(){const t=document.querySelector(".loader");t&&t.remove()}
//# sourceMappingURL=index.js.map
